# Generated by Django 4.0 on 2022-01-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100, unique=True)),
                ('last_completed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
