# Generated by Django 4.0 on 2022-01-03 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_chore_last_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='last_completed',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 2, 21, 54, 2, 573793)),
        ),
    ]
