# Generated by Django 4.0 on 2022-01-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_chore_last_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='last_completed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
