# Generated by Django 4.0 on 2022-01-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_chore_last_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
