# Generated by Django 4.0 on 2022-01-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_chore_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
