# Generated by Django 4.0 on 2022-01-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_chore_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
